### ISSUE TITLE
script fails

### ISSUE THREAD

**Issue by terreb** [SolidStateGroup/react-native-app-id#1]
Not sure whether this is critical and the script failed or succeeded:

(node:60103) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Could not detect ios app id from plist
(node:60103) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by kyle-ssg** [comment]
Spent a bit of time on this, fixed in latest release
